name: Sample
on:
  workflow_dispatch:

permissions:
  contents: read # This is required for actions/checkout
  actions: read # this is required for read the actions

env:
  LOREM: IPSUM


jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - shell: bash
        name: get env
        run: |
            echo "repo : "${{ env.GITHUB_REPOSITORY }}
            echo "-------------------"
            env
            echo "-------------------"
            ${{ env.GITHUB_REPOSITORY }}
            echo "-------------------"
            echo ${{ github.repository }}
            echo "-------------------"
            echo "${{ github.repository }}"
